version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ticket_system

  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles  # Ensure static files are persisted
      - media_volume:/app/media
    env_file:
      - .env

volumes:
  pg_data:
  static_volume:
  media_volume:
