from django.urls import path
from . import views
from .views import (
    home, register, login_view, logout_view, change_password, set_language,
    user_list, user_create, user_update, user_delete, manage_user_roles,
    role_list, role_create, role_update, role_delete,
    dashboard, feedback, update_ticket_order, inline_edit,
    ticket_list, ticket_detail, ticket_update_status, ticket_add_note,
    ticket_reassign, ticket_transfer, ticket_create, ticket_update,
    ticket_delete, department_list, department_create, department_update,
    department_delete, request_type_list, request_type_create,
    request_type_update, request_type_delete, sub_request_type_list,
    sub_request_type_create, sub_request_type_update, sub_request_type_delete,
    get_sub_request_types, get_request_types, position_list, position_create,
    position_update, position_delete, sub_position_list, sub_position_create,
    sub_position_update, sub_position_delete, company_settings,
    financial_warehouse_list, financial_warehouse_create, financial_warehouse_update,
    financial_warehouse_delete, hr_warehouse_list, hr_warehouse_create,
    hr_warehouse_update, hr_warehouse_delete, employee_details_list,
    employee_details_create, employee_details_update, employee_details_delete,
    administrative_request_list, administrative_request_create,
    administrative_request_update, administrative_request_delete,
    technical_office_storage_list, technical_office_storage_create,
    technical_office_storage_update, technical_office_storage_delete,
    it_warehouse_list, it_warehouse_create, it_warehouse_update, it_warehouse_delete,
    it_request_list, it_request_create, it_request_update, it_request_delete,
    my_possession_list, my_possession_create, my_possession_update,
    my_possession_delete, contractor_list, contractor_create, contractor_update,
    contractor_delete, company_clearance_list, company_clearance_create, company_clearance_delete, erp_list, erp_create,
    erp_update, erp_delete, accounting_list, accounting_create, accounting_update,
    accounting_delete, crm_customer_list, crm_customer_create, crm_customer_update,
    crm_customer_delete, crm_lead_list, crm_lead_create, crm_lead_update, crm_lead_delete,
    journal_entry_list, journal_entry_create, journal_entry_update, journal_entry_delete,
    journal_entry_line_list, journal_entry_line_create, journal_entry_line_update,
    journal_entry_line_delete, salary_list, salary_create, salary_update, salary_delete,
    employee_allowance_list, employee_allowance_create, employee_allowance_update,
    employee_allowance_delete, financial_advance_list, financial_advance_create,
    financial_advance_update, financial_advance_delete, end_of_service_reward_list,
    end_of_service_reward_create, end_of_service_reward_update, end_of_service_reward_delete, start_work_permit_update_status, 
    export_tickets_to_pdf, export_users_to_pdf, export_roles_to_pdf, export_departments_to_pdf, export_request_types_to_pdf,
    export_positions_to_pdf, export_company_settings_to_pdf, export_it_requests_to_pdf, export_it_warehouse_to_pdf, export_company_clearance_pdf,
    ticket_search_view, notifications, it_request_update_status, export_work_permits_to_pdf, export_work_permit_to_pdf, update_clearance_status,
    export_admin_requests_to_pdf, update_manager_approval, update_gm_approval, start_work_permit_list, update_work_permit_status,
    export_employee_details_to_pdf,
)

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('change_password/', change_password, name='change_password'),
    path('set_language/', set_language, name='set_language'),
    path('users/', user_list, name='user_list'),
    path('users/create/', user_create, name='user_create'),
    path('users/<int:pk>/update/', user_update, name='user_update'),
    path('users/<int:pk>/delete/', user_delete, name='user_delete'),
    path('users/<int:pk>/roles/', manage_user_roles, name='manage_user_roles'),
    path('roles/', role_list, name='role_list'),
    path('roles/create/', role_create, name='role_create'),
    path('roles/<int:pk>/update/', role_update, name='role_update'),
    path('roles/<int:pk>/delete/', role_delete, name='role_delete'),
    path('dashboard/', dashboard, name='dashboard'),
    
    # Placeholder URLs for the dropdown menu links
    path('feedback/', feedback, name='feedback'),
    path('tickets/', ticket_list, name='ticket_list'),
    path('tickets/<int:pk>/', ticket_detail, name='ticket_detail'),
    path('tickets/<int:pk>/status/', ticket_update_status, name='ticket_update_status'),
    path('tickets/<int:pk>/note/', ticket_add_note, name='ticket_add_note'),
    path('tickets/<int:pk>/reassign/', ticket_reassign, name='ticket_reassign'),
    path('tickets/<int:pk>/transfer/', ticket_transfer, name='ticket_transfer'),
    path('tickets/create/', ticket_create, name='ticket_create'),
    path('tickets/<int:pk>/update/', ticket_update, name='ticket_update'),
    path('tickets/<int:pk>/delete/', ticket_delete, name='ticket_delete'),
    path('departments/', department_list, name='department_list'),
    path('departments/create/', department_create, name='department_create'),
    path('departments/<int:pk>/update/', department_update, name='department_update'),
    path('departments/<int:pk>/delete/', department_delete, name='department_delete'),
    path('request_types/', request_type_list, name='request_type_list'),
    path('request_types/create/', request_type_create, name='request_type_create'),
    path('request_types/<int:pk>/update/', request_type_update, name='request_type_update'),
    path('request_types/<int:pk>/delete/', request_type_delete, name='request_type_delete'),
    path('sub_request_types/<int:request_type_id>/', sub_request_type_list, name='sub_request_type_list'),
    path('sub_request_types/<int:request_type_id>/create/', sub_request_type_create, name='sub_request_type_create'),
    path('sub_request_types/<int:pk>/update/', sub_request_type_update, name='sub_request_type_update'),
    path('sub_request_types/<int:pk>/delete/', sub_request_type_delete, name='sub_request_type_delete'),
    path('positions/', position_list, name='position_list'),
    path('positions/create/', position_create, name='position_create'),
    path('positions/<int:pk>/update/', position_update, name='position_update'),
    path('positions/<int:pk>/delete/', position_delete, name='position_delete'),
    path('sub_positions/', sub_position_list, name='sub_position_list'),
    path('sub_positions/<int:position_id>/create/', sub_position_create, name='sub_position_create'),
    path('sub_positions/<int:pk>/update/', sub_position_update, name='sub_position_update'),
    path('sub_positions/<int:pk>/delete/', sub_position_delete, name='sub_position_delete'),
    path('company_settings/', company_settings, name='company_settings'),
    path('financial_warehouse/', financial_warehouse_list, name='financial_warehouse_list'),
    path('financial_warehouse/create/', financial_warehouse_create, name='financial_warehouse_create'),
    path('financial_warehouse/<int:pk>/update/', financial_warehouse_update, name='financial_warehouse_update'),
    path('financial_warehouse/<int:pk>/delete/', financial_warehouse_delete, name='financial_warehouse_delete'),
    path('financial-warehouse-requests/', views.financial_warehouse_request_list, name='financial_warehouse_request_list'),
    path('hr_warehouse/', hr_warehouse_list, name='hr_warehouse_list'),
    path('hr_warehouse/create/', hr_warehouse_create, name='hr_warehouse_create'),
    path('hr_warehouse/<int:pk>/update/', hr_warehouse_update, name='hr_warehouse_update'),
    path('hr_warehouse/<int:pk>/delete/', hr_warehouse_delete, name='hr_warehouse_delete'),
    path('employee_details/', employee_details_list, name='employee_details_list'),
    path('employee_details/create/', employee_details_create, name='employee_details_create'),
    path('employee_details/<int:pk>/update/', employee_details_update, name='employee_details_update'),
    path('employee_details/<int:pk>/delete/', employee_details_delete, name='employee_details_delete'),
    path('administrative_requests/', administrative_request_list, name='administrative_request_list'),
    path('administrative_requests/create/', administrative_request_create, name='administrative_request_create'),
    path('administrative_requests/<int:pk>/update/', administrative_request_update, name='administrative_request_update'),
    path('administrative_requests/<int:pk>/delete/', administrative_request_delete, name='administrative_request_delete'),
    path('technical_office_storage/', technical_office_storage_list, name='technical_office_storage_list'),
    path('technical_office_storage/create/', technical_office_storage_create, name='technical_office_storage_create'),
    path('technical_office_storage/<int:pk>/update/', technical_office_storage_update, name='technical_office_storage_update'),
    path('technical_office_storage/<int:pk>/delete/', technical_office_storage_delete, name='technical_office_storage_delete'),
    path('it_warehouse/', it_warehouse_list, name='it_warehouse_list'),
    path('it_warehouse/create/', it_warehouse_create, name='it_warehouse_create'),
    path('it_warehouse/<int:pk>/update/', it_warehouse_update, name='it_warehouse_update'),
    path('it_warehouse/<int:pk>/delete/', it_warehouse_delete, name='it_warehouse_delete'),
    path('it_requests/', it_request_list, name='it_request_list'),
    path('it_requests/create/', it_request_create, name='it_request_create'),
    path('it_requests/<int:pk>/update/', it_request_update, name='it_request_update'),
    path('it_requests/<int:pk>/delete/', it_request_delete, name='it_request_delete'),
    path('my_possessions/', my_possession_list, name='my_possession_list'),
    path('my_possessions/create/', my_possession_create, name='my_possession_create'),
    path('my_possessions/<int:pk>/update/', my_possession_update, name='my_possession_update'),
    path('my_possessions/<int:pk>/delete/', my_possession_delete, name='my_possession_delete'),
    path('contractors/', contractor_list, name='contractor_list'),
    path('contractors/create/', contractor_create, name='contractor_create'),
    path('contractors/<int:pk>/update/', contractor_update, name='contractor_update'),
    path('contractors/<int:pk>/delete/', contractor_delete, name='contractor_delete'),
    path('erp_entries/', erp_list, name='erp_list'),
    path('erp_entries/create/', erp_create, name='erp_create'),
    path('erp_entries/<int:pk>/update/', erp_update, name='erp_update'),
    path('erp_entries/<int:pk>/delete/', erp_delete, name='erp_delete'),
    path('accounting_entries/', accounting_list, name='accounting_entries'),
    path('accounting_entries/create/', accounting_create, name='accounting_entries_create'),
    path('accounting_entries/<int:pk>/update/', accounting_update, name='accounting_entries_update'),
    path('accounting_entries/<int:pk>/delete/', accounting_delete, name='accounting_entries_delete'),
    path('crm_customers/', crm_customer_list, name='crm_customer_list'),
    path('crm_customers/create/', crm_customer_create, name='crm_customer_create'),
    path('crm_customers/<int:pk>/update/', crm_customer_update, name='crm_customer_update'),
    path('crm_customers/<int:pk>/delete/', crm_customer_delete, name='crm_customer_delete'),
    path('crm_leads/', crm_lead_list, name='crm_lead_list'),
    path('crm_leads/create/', crm_lead_create, name='crm_lead_create'),
    path('crm_leads/<int:pk>/update/', crm_lead_update, name='crm_lead_update'),
    path('crm_leads/<int:pk>/delete/', crm_lead_delete, name='crm_lead_delete'),
    path('journal_entries/', journal_entry_list, name='journal_entry_list'),
    path('journal_entries/create/', journal_entry_create, name='journal_entry_create'),
    path('journal_entries/<int:pk>/update/', journal_entry_update, name='journal_entry_update'),
    path('journal_entries/<int:pk>/delete/', journal_entry_delete, name='journal_entry_delete'),
    path('journal_entry_lines/', journal_entry_line_list, name='journal_entry_line_list'),
    path('journal_entry_lines/create/', journal_entry_line_create, name='journal_entry_line_create'),
    path('journal_entry_lines/<int:pk>/update/', journal_entry_line_update, name='journal_entry_line_update'),
    path('journal_entry_lines/<int:pk>/delete/', journal_entry_line_delete, name='journal_entry_line_delete'),
    path('salaries/', salary_list, name='salary_list'),
    path('salaries/create/', salary_create, name='salary_create'),
    path('salaries/<int:pk>/update/', salary_update, name='salary_update'),
    path('salaries/<int:pk>/delete/', salary_delete, name='salary_delete'),
    path('employee_allowances/', employee_allowance_list, name='employee_allowance_list'),
    path('employee_allowances/create/', employee_allowance_create, name='employee_allowance_create'),
    path('employee_allowances/<int:pk>/update/', employee_allowance_update, name='employee_allowance_update'),
    path('employee_allowances/<int:pk>/delete/', employee_allowance_delete, name='employee_allowance_delete'),
    path('financial_advances/', financial_advance_list, name='financial_advance_list'),
    path('financial_advances/create/', financial_advance_create, name='financial_advance_create'),
    path('financial_advances/<int:pk>/update/', financial_advance_update, name='financial_advance_update'),
    path('financial_advances/<int:pk>/delete/', financial_advance_delete, name='financial_advance_delete'),
    path('end_of_service_rewards/', end_of_service_reward_list, name='end_of_service_reward_list'),
    path('end_of_service_rewards/create/', end_of_service_reward_create, name='end_of_service_reward_create'),
    path('end_of_service_rewards/<int:pk>/update/', end_of_service_reward_update, name='end_of_service_reward_update'),
    path('end_of_service_rewards/<int:pk>/delete/', end_of_service_reward_delete, name='end_of_service_reward_delete'),
    path('export/tickets_to_pdf/', export_tickets_to_pdf, name='export_tickets_to_pdf'),
    path('export/users/pdf/', export_users_to_pdf, name='export_users_to_pdf'),
    path('export/roles/pdf/', export_roles_to_pdf, name='export_roles_to_pdf'),
    path('export/departments/pdf/', export_departments_to_pdf, name='export_departments_to_pdf'),
    path('export/request_types/pdf/', export_request_types_to_pdf, name='export_request_types_to_pdf'),
    path('export/positions/pdf/', export_positions_to_pdf, name='export_positions_to_pdf'),
    path('export/company_settings/pdf/', export_company_settings_to_pdf, name='export_company_settings_to_pdf'),
    path('search/tickets/', ticket_search_view, name='ticket_search_view'),
    path('notifications/', notifications, name='notifications'),
    path('tickets/<int:pk>/update_order/', update_ticket_order, name='update_ticket_order'),
    path('tickets/<int:pk>/inline_edit/', inline_edit, name='inline_edit'),
    path('sub_request_types/<int:request_type_id>/list/', get_sub_request_types, name='get_sub_request_types'),
    path('request_types/list/', get_request_types, name='get_request_types'),
    path('export/employee_details/pdf/', views.export_employee_details_to_pdf, name='export_employee_details_to_pdf'),
    path('it_warehouse/', views.it_warehouse_list, name='it_warehouse_list'),
    path('it_warehouse/create/', views.it_warehouse_create, name='it_warehouse_create'),
    path('it_warehouse/<int:pk>/', views.it_warehouse_detail, name='it_warehouse_detail'),
    path('it_warehouse/<int:pk>/update/', views.it_warehouse_update, name='it_warehouse_update'),
    path('it_warehouse/<int:pk>/delete/', views.it_warehouse_delete, name='it_warehouse_delete'),
    path('it_requests/', it_request_list, name='it_request_list'),
    path('it_requests/create/', it_request_create, name='it_request_create'),
    path('export/it_requests/pdf/', views.export_it_requests_to_pdf, name='export_it_requests_to_pdf'),
    path('login/', login_view, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout_view, name='logout'),
    path('update-manager-approval/', update_manager_approval, name='update_manager_approval'),
    path('update-gm-approval/', update_gm_approval, name='update_gm_approval'),
    path('export/financial_warehouse/pdf/', views.export_financial_warehouse_to_pdf, name='export_financial_warehouse_to_pdf'),
    path('export/admin_requests/pdf/', views.export_admin_requests_to_pdf, name='export_admin_requests_to_pdf'),
    path('export/hr_warehouse/pdf/', views.export_hr_warehouse_to_pdf, name='export_hr_warehouse_to_pdf'),
    path('export/it_warehouse/pdf/', export_it_warehouse_to_pdf, name='export_it_warehouse_to_pdf'),
    path('ticket/<int:pk>/add-note/', ticket_add_note, name='ticket_add_note'),
    path('it-request/<int:pk>/update-status/', views.it_request_update_status, name='it_request_update_status'),
    path('financial-warehouse/assign/<int:pk>/', views.assign_item, name='assign_item'),
    path('start-work-permits/', views.start_work_permit_list, name='start_work_permit_list'),
    path('start-work-permits/create/', views.start_work_permit_create, name='start_work_permit_create'),
    path('start-work-permits/update/<int:pk>/', views.start_work_permit_update, name='start_work_permit_update'),
    path('start-work-permits/delete/<int:pk>/', views.start_work_permit_delete, name='start_work_permit_delete'),
    path('start-work-permits/export/pdf/', views.export_work_permits_to_pdf, name='export_work_permits_to_pdf'),
    path('work-permit/<int:pk>/update-status/', start_work_permit_update_status, name='start_work_permit_update_status'),
    path('export_work_permit/', export_work_permit_to_pdf, name='export_work_permit_pdf'),
    path('start-work-permits/', start_work_permit_list, name='start_work_permit_list'),
    path('start-work-permits/update-status/<int:pk>/', update_work_permit_status, name='update_work_permit_status'),
    path('company-clearances/', company_clearance_list, name='company_clearance_list'),
    path('company-clearance/create/', company_clearance_create, name='company_clearance_create'),
    path('company-clearance/delete/<int:pk>/', company_clearance_delete, name='company_clearance_delete'),
    path('export-company-clearance/', export_company_clearance_pdf, name='export_company_clearance_pdf'),
    path('company-clearances/<int:pk>/update-status/', update_clearance_status, name='update_clearance_status'),
]

